steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:  ['/workspace/buildscripts/copybins.sh','${_DIST_BUCKET}','$BRANCH_NAME']
- name: gcr.io/kaniko-project/executor:latest
  args:
      - --destination=gcr.io/$PROJECT_ID/hybrics-bin:$BRANCH_NAME
      - --cache=false
      - --target=builder
      - --cache-ttl=10h
      - --dockerfile=Dockerfile
- name: gcr.io/kaniko-project/executor:latest
  args:
      - --destination=gcr.io/$PROJECT_ID/hybrics:$BRANCH_NAME
      - --cache=false
      - --cache-ttl=10h
      - --dockerfile=Dockerfile
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "mkdir pkgs/" ]
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: [ '-c', 'docker run --rm gcr.io/hybrics/hybrics-bin:$BRANCH_NAME | tar --extract --verbose -C pkgs/']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gsutil cp pkgs/*.* gs://${_DIST_BUCKET}/pkgs/" ]
substitutions:
  _DIST_BUCKET: abucket # default value
timeout: 10800s
options:
  machineType: 'N1_HIGHCPU_32'