steps:

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:  ['/workspace/buildscripts/copybins.sh','${_DIST_BUCKET}','$BRANCH_NAME']
- name: gcr.io/kaniko-project/executor:latest
  args:
      - --destination=gcr.io/$PROJECT_ID/hybrics-bin:$BRANCH_NAME
      - --cache=false
      - --target=builder
      - --cache-ttl=10h
      - --dockerfile=Dockerfile
  env:
  - 'VERSION=${BRANCH_NAME}'
  - 'PKG_VERSION=0.0.1'
- name: gcr.io/kaniko-project/executor:latest
  args:
      - --destination=gcr.io/$PROJECT_ID/hybrics:$BRANCH_NAME
      - --cache=false
      - --cache-ttl=10h
      - --dockerfile=Dockerfile
  env:
  - 'VERSION=${BRANCH_NAME}'
  - 'PKG_VERSION=0.0.1'
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull  gcr.io/$PROJECT_ID/hybrics:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker tag  gcr.io/$PROJECT_ID/hybrics:$BRANCH_NAME $$USERNAME/sdfs:$BRANCH_NAME']
  secretEnv: ['USERNAME']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push $$USERNAME/sdfs:$BRANCH_NAME']
  secretEnv: ['USERNAME']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "mkdir pkgs/" ]
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: [ '-c', 'docker run --rm gcr.io/hybrics/hybrics-bin:$BRANCH_NAME | tar --extract --verbose -C pkgs/']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gsutil cp pkgs/*.* gs://${_DIST_BUCKET}/pkgs/" ]
substitutions:
  _DIST_BUCKET: abucket # default value
timeout: 10800s
options:
  machineType: 'N1_HIGHCPU_32'
availableSecrets:
   secretManager:
   - versionName: projects/$PROJECT_NUMBER/secrets/docker-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/$PROJECT_NUMBER/secrets/docker-username/versions/1
     env: 'USERNAME'