steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
  - "-c"
  - |-
    gsutil cp gs://${_DIST_BUCKET}/sdfscli/sdfscli-$BRANCH_NAME /tmp/ 
    rm -rf /workspace/install-packages/deb/sbin/sdfscli
    rm -rf /workspace/install-packages/deb/usr/share/sdfs/sdfscli
    cp /tmp/sdfscli-$BRANCH_NAME  /workspace/install-packages/deb/sbin/sdfscli 
    cp /tmp/sdfscli-$BRANCH_NAME  /workspace/install-packages/deb/usr/share/sdfs/sdfscli
    rm /tmp/sdfscli-$BRANCH_NAME
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: ["gsutil cp gs://${_DIST_BUCKET}/hybrics-fs/mount.sdfs-$BRANCH_NAME /tmp/ 
    && rm -rf /workspace/install-packages/deb/sbin/mount.sdfs
    && rm -rf /workspace/install-packages/deb/usr/share/sdfs/mount.sdfs
    && cp /tmp/mount.sdfs-$BRANCH_NAME  /workspace/install-packages/deb/sbin/mount.sdfs 
    && cp /tmp/mount.sdfs-$BRANCH_NAME  /workspace/install-packages/deb/usr/share/sdfs/mount.sdfs"]
- name: gcr.io/kaniko-project/executor:latest
  args:
      - --destination=gcr.io/$PROJECT_ID/hybrics:$BRANCH_NAME
      - --cache=false
      - --target=builder
      - --cache-ttl=10h
      - --dockerfile=Dockerfile
- name: gcr.io/kaniko-project/executor:latest
  args:
      - --destination=gcr.io/$PROJECT_ID/hybrics:$BRANCH_NAME
      - --cache=false
      - --cache-ttl=10h
      - --dockerfile=Dockerfile
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "mkdir pkgs/" ]
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: [ '-c', 'docker run --rm gcr.io/hybrics/hybrics-build:$BRANCH_NAME | tar --extract --verbose -C pkgs/']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gsutil cp pkgs/*.* gs://${_DIST_BUCKET}/pkgs/" ]
substitutions:
  _DIST_BUCKET: abucket # default value
timeout: 10800s
options:
  machineType: 'N1_HIGHCPU_32'