steps:
- name: gcr.io/kaniko-project/executor:latest
  args:
    - --destination=gcr.io/$PROJECT_ID/hybrics-build:$BRANCH_NAME
    - --cache=true
    - --cache-ttl=10h
    - --cleanup
    - --target=builder
    - --dockerfile=Dockerfile
- name: gcr.io/kaniko-project/executor:latest
  args:
      - --destination=gcr.io/$PROJECT_ID/hybrics:$BRANCH_NAME
      - --cache=true
      - --cache-ttl=10h
      - --cleanup
      - --dockerfile=Dockerfile
timeout: 10800s
options:
  machineType: 'N1_HIGHCPU_32'